### ISSUE TITLE
Can’t use :contains with unbalanced parentheses in text

### ISSUE THREAD

**Issue by Aankhen** [fb55/css-select#107]
(I figure this is a css-select issue rather than a css-what issue, since `:contains` isn’t a real CSS selector, but if not, I can re-file it there.)

Trying to match an element containing text which includes unbalanced parentheses causes a syntax error. Here’s an example:

```js
const cssSelect = require("css-select");

const input = [
  ":contains(hello)",
  ":contains(hello ())",
  ":contains('hello ()')",
  ":contains(\"hello ()\")",
  ":contains('hello (')",
  ":contains(\"hello (\")",
  ":contains(hello \\()",
];

for (const s of input) {
  try {
    console.log(s, typeof cssSelect.compile(s));
  } catch (e) {
    console.error(s, e.message);
  }
}
```

Output:
```
:contains(hello) function
:contains(hello ()) function
:contains('hello ()') function
:contains("hello ()") function
:contains('hello (') parenthesis not matched
:contains("hello (") parenthesis not matched
:contains(hello \() parenthesis not matched
```

Here’s one of the errors in full:

```
:contains('hello (') SyntaxError: parenthesis not matched
    at parseSelector (/firharvesting/puppeteer/node_modules/css-what/index.js:219:14)
    at parse (/firharvesting/puppeteer/node_modules/css-what/index.js:82:13)
    at compileUnsafe (/firharvesting/puppeteer/node_modules/css-select/lib/compile.js:31:14)
    at Function.compile (/firharvesting/puppeteer/node_modules/css-select/lib/compile.js:20:13)
    at Object.<anonymous> (/firharvesting/puppeteer/test.js:12:30)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by Aankhen** [comment]
I see [this has already been fixed in css-what](https://github.com/fb55/css-what/commit/c636f0d9267f21dfb7490441fe49bdcdb0a084ef) but the new version isn’t on npm. Would it be possible to publish it?

**Comment by fb55** [comment]
Looks like this has been fixed!
