### ISSUE TITLE
Test fails with domutils ≥ 2.0.0

### ISSUE THREAD

**Issue by guimard** [fb55/css-select#157]
Hi,

when using an updated domutils, css-select test fails:
```
  153 passing (348ms)
  2 failing

  1) nwmatcher
       Attribute Selectors
         E[foo]:
     AssertionError [ERR_ASSERTION]: li#item_3[class]
      at Object.E[foo] (test/nwmatcher/index.js:152:18)
      at Context.<anonymous> (test/nwmatcher/index.js:62:33)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:354:21)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:346:7)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:442:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:560:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:356:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:366:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:290:14)
      at Immediate._onImmediate (/usr/lib/nodejs/mocha/lib/runner.js:334:5)

  2) sizzle
       selector
         attributes:

      AssertionError [ERR_ASSERTION]: Object.prototype property "constructor" (negative) ([constructor])
      + expected - actual

      -[
      -  "html",
      -  null,
      -  null,
      -  null,
      -  null,
      -  null,
      -  null,
      -  null,
      -  null,
      -  null,
      -  null,
      -  null,
      -  "body",
      -  "qunit",
      -  "qunit-header",
      -  "qunit-banner",
      -  "qunit-testrunner-toolbar",
      -  "qunit-userAgent",
      -  "dl",
      -  "qunit-fixture",
      -  "firstp",
      -  "simon1",
      -  "ap",
      -  "google",
      -  "groups",
[...]
```

**Comment by guimard** [comment]
I had to disable these 2 tests:
```diff
--- a/test/nwmatcher/index.js
+++ b/test/nwmatcher/index.js
@@ -149,7 +149,7 @@
         "E[foo]": function() {
             this.assertEquivalent(select("h1[class]"), select("#fixtures h1"), "h1[class]");
             this.assertEquivalent(select("h1[CLASS]"), select("#fixtures h1"), "h1[CLASS]");
-            this.assertEqual(select("li#item_3[class]")[0], getById("item_3"), "li#item_3[class]");
+            //this.assertEqual(select("li#item_3[class]")[0], getById("item_3"), "li#item_3[class]");
             this.assertEquivalent(
                 select('#troubleForm2 input[name="brackets[5][]"]'),
                 getById("chk_1", "chk_2")
--- a/test/sizzle/selector.js
+++ b/test/sizzle/selector.js
@@ -888,7 +888,7 @@
     );

     div = document.getElementById("foo");
-    t('Object.prototype property "constructor" (negative)', "[constructor]", []);
+    //t('Object.prototype property "constructor" (negative)', "[constructor]", []);
     t('Gecko Object.prototype property "watch" (negative)', "[watch]", []);
     div.attribs.constructor = "foo";
     div.attribs.watch = "bar";
```

**Comment by fb55** [comment]
This was caused by a bug in domutils. Fixed the bug, tests for css-select are passing now.

**Comment by guimard** [comment]
@fb55: thanks! I just updated Debian package
