### ISSUE TITLE
TypeError: ext[key].bind is not a function

### ISSUE THREAD

**Issue by milindsingh** [fb55/css-select#339]
I am facing this error in strapi heroku start. Can anyone direct me in the right direction?

```
[2021-01-09T09:47:25.184Z] error TypeError: ext[key].bind is not a function
api-cms-adapttive-com | 15:17:25     at /workspace/node_modules/css-select/node_modules/domutils/index.js:12:28
api-cms-adapttive-com | 15:17:25     at Array.forEach (<anonymous>)
api-cms-adapttive-com | 15:17:25     at /workspace/node_modules/css-select/node_modules/domutils/index.js:11:19
api-cms-adapttive-com | 15:17:25     at Array.forEach (<anonymous>)
api-cms-adapttive-com | 15:17:25     at Object.<anonymous> (/workspace/node_modules/css-select/node_modules/domutils/index.js:10:3)
api-cms-adapttive-com | 15:17:25     at Module._compile (internal/modules/cjs/loader.js:1063:30)
api-cms-adapttive-com | 15:17:25     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
api-cms-adapttive-com | 15:17:25     at Module.load (internal/modules/cjs/loader.js:928:32)
api-cms-adapttive-com | 15:17:25     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
api-cms-adapttive-com | 15:17:25     at Module.require (internal/modules/cjs/loader.js:952:19)
api-cms-adapttive-com | 15:17:25 error Command failed with exit code 1.
```

**Comment by fb55** [comment]
Bug from an old version. Please upgrade!
