### ISSUE TITLE
Cannot read property 'Descendant' of undefined when update to webpack 5.71.0

### ISSUE THREAD

**Issue by jquintozamora** [fb55/css-select#738]
When updating to webpack 5.71.0, then I'm having this issue: 

[webpack-cli] TypeError: Cannot read property 'Descendant' of undefined
    at Object.<anonymous> (/home/vsts/work/1/s/node_modules/css-select/lib/compile.js:36:56)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/vsts/work/1/s/node_modules/css-select/lib/index.js:29:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by jquintozamora** [comment]
Sorry for confusion, solved, it was related to a different update

**Comment by MichaelDimitrasSentiLink** [comment]
I was getting this same error.  It was because I had an old version of css-what in my resolutions.  Bumping to css-what 6.1.0 fixed it.

**Comment by rachelslurs** [comment]
Same here. It was because i was trying to fix an issue with enzyme by pinning a version of cheerio in my package.json https://github.com/enzymejs/enzyme/issues/2518#issuecomment-1133956378
